In [1]:
def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("Not Possible")
except:
    print("Any other exception")


Not Possible


In [2]:
subject=["Americans", "Indians"]
verb=["play", "watch"]
object=["Baseball","cricket"]
sentences = [(subj+" "+ veb + " " + obj) for subj in subject for veb in verb for obj in object]
for sentence in sentences:
 print (sentence)

Americans play Baseball
Americans play cricket
Americans watch Baseball
Americans watch cricket
Indians play Baseball
Indians play cricket
Indians watch Baseball
Indians watch cricket


In [11]:
import numpy as np
def matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx


inputvector = np.array([2,3,4])
no_col_opmat = 3
op_matx_dec_order = matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = matrix(inputvector,no_col_opmat,True)

print(inputvector,"\n")
print(op_matx_dec_order,"\n")
print(op_matx_inc_order,"\n")



[2 3 4] 

[[ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 

[[ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]] 

